# Generated by Django 2.2 on 2019-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.DecimalField(decimal_places=3, max_digits=5)),
                ('right', models.DecimalField(decimal_places=3, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=3, max_digits=5)),
                ('left', models.DecimalField(decimal_places=3, max_digits=5)),
                ('image', models.ForeignKey(on_delete='CASCADE', to='face.Url')),
            ],
        ),
    ]
