# Generated by Django 2.2.1 on 2019-05-07 08:09

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to=bank.models.customer_image_file_path),
        ),
    ]
