# Generated by Django 2.2.1 on 2019-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
    ]
