# Generated by Django 2.2.1 on 2019-05-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20190521_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='bank.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='bank.Account'),
        ),
    ]
